export const summaryData = {
  key: "2023-06-12T00:00:00-04:002023-06-12T23:59:59-04:00",
  comparisons: [
    {
      totalSales: 5.087931860355596,
      newCustomerSales: 16.572140586061696,
      netSales: 5.087931860355596,
      rcRevenue: -1.7948305275694392,
      totalPaymentGatewayCosts: 54.673149648838496,
      totalProductCosts: 36.61535143296219,
      totalHandlingFees: 0,
      totalCustomSpends: 0,
      totalInventoryItems: 0,
      totalInventoryItemsMissing: 0,
      totalInventoryCost: 0,
      totalInventoryValue: 0,
      shopifyAov: -8.048059622188855,
      averageGaRevenuePerTransaction: -8.048059622188855,
      fb_ads_spend: 22.96458561518801,
      ga_adCost: 22.944005239174487,
      googleAllCpa: 100,
      googleBounceRate: -2.5944202002697865,
      googleConversionValue: 100,
      totalSnapchatSpend: 0,
      totalSnapchatRoas: 0,
      snapchatImpressions: 0,
      snapchat_swipes: 0,
      snapchatCpm: 0,
      snapchatCpa: 0,
      totalSnapchatConversionPurchasesValue: 0,
      averageGaTransactionsPerSession: -4.349108064278328,
      totalGoogleAnalyticsSessions: 19.482120838471022,
      totalOrders: 14.285714285714286,
      totalNetProfit: -43.186962835380236,
      cashTurnover: -15.976390711874975,
      totalNetMargin: -45.93761989710213,
      totalCpa: 7.592961801156989,
      totalRevenuePerSession: -12.047148876420657,
      totalRefunds: 0,
      fb_ads_purchase_roas: 97.62014471276626,
      ga_ROAS: 100,
      totalGoogleAdsCtr: 10.139480195261141,
      totalGoogleAdsCpm: 23.531827924322663,
      googleCpc: 12.159443376089003,
      totalGoogleAdsClicks: 9.615384615384615,
      totalGoogleAdsImpressions: -0.47584715212689255,
      ga_transactions_adGroup: 100,
      ga_all_transactionsRevenue_adGroup: 100,
      ga_all_transactions_adGroup: 100,
      totalAllRoas: 100,
      googleCpa: 100,
      averageFacebookCpc: -13.277608039814766,
      facebookViewThrough: 0,
      facebookViewThroughRoas: 0,
      facebookViewThroughCpa: 0,
      averageFacebookCpm: -6.827568655638538,
      facebookCtr: 7.4375708953432405,
      facebookCostPerOutboundClick: -6.3957527941122,
      facebookConversionValue: 143.00279203818795,
      facebookWebConversionValue: 143.00279203818795,
      facebookMetaConversionValue: 0,
      facebookRevenuePerClick: 84.98084878557093,
      facebookCpa: -56.9623950346842,
      facebookPurchases: 185.71428571428572,
      facebookMetaPurchases: 0,
      facebookWebPurchases: 185.71428571428572,
      newCustomersCpa: -15.462672870519503,
      totalKlaviyoPlacedOrderSalesPercent: 10.539316128134763,
      totalKlaviyoPlacedOrderSalesPercentFlows: 10.539316128134763,
      totalKlaviyoPlacedOrderSalesPercentCampaigns: 0,
      klaviyoEmailOpenRate: 0,
      totalKlaviyoUnsubscribed: 200,
      totalKlaviyoPlacedOrderTotalPriceFlows: 16.163481211637315,
      totalKlaviyoPlacedOrderTotalPriceCampaigns: 0,
      totalKlaviyoSubscribedToList: 66.66666666666667,
      totalKlaviyoClickedEmail: 30.76923076923077,
      totalKlaviyoReceivedEmail: -12.318840579710145,
      totalKlaviyoClickedSms: 0,
      klaviyoCVR: 30.34238488783943,
      klaviyoRevenuePerEmail: 19.85235203908323,
      totalKlaviyoNetNewSubscribers: 40,
      klaviyoPlacedOrderSales: 16.163481211637315,
      attentivePlacedOrderSales: 0,
      totalAttentivePlacedOrder: 0,
      totalAttentiveNewSubscribed: 0,
      totalAttentiveNetNewsubscribers: 0,
      totalAttentiveUnsubscribed: 0,
      totalAttentivePlacedOrderSalesPercent: 0,
      totalAttentivePlacedOrderTotalPriceFlows: 0,
      totalAttentivePlacedOrderSalesPercentFlows: 0,
      totalAttentivePlacedOrderTotalPriceCampaigns: 0,
      totalAttentivePlacedOrderSalesPercentCampaigns: 0,
      tiktok_spend: 0,
      tiktok_complete_payment_roas: 0,
      tiktokImpressions: 0,
      averageTiktokCpm: 0,
      averageTiktokCpc: 0,
      tiktokCtr: 0,
      tiktokCpa: 0,
      tiktokConversionValue: 0,
      tiktokPurchases: 0,
      uniqueCustomerLifetimeValue: 639.994186850004,
      customerFrequency: 704.7619047619048,
      ltvCpa: 587.7719271429579,
      mer: 17.009996046935154,
      totalReturns: 0,
      totalTaxes: 20.435139573070593,
      newCustomersPercent: 27.272727272727284,
      oldCustomersPercent: -9.677419354838724,
      newCustomersOrders: 45.45454545454545,
      getUniqueCustomerCount: -85.79881656804734,
      totalShippingCosts: 14.285714285714286,
      totalGoogleAnalyticsUsers: 19.851116625310173,
      totalGorgiasTicketsCreated: 0,
      totalGorgiasTicketsReplied: 0,
      averageGorgiasResponseTime: 0,
      averageGorgiasResolutionTime: 0,
      totalVariantsSold: 3.7974683544303796,
      blendedAds: 22.96338491560799,
      totalRoas: -14.855072463768106,
      newCustomersRoas: -4.854368932038839,
      blendedAttributedRoas: 108.06451612903226,
      poas: -23.82706659117826,
      shopifyCpa: 7.592961801156989,
      pinterestSpend: 0,
      pinterestRoas: 0,
      pinterestCpc: 0,
      pinterestCpm: 0,
      pinterestConversionValue: 0,
      pinterestPurchases: 0,
      pinterestImpressions: 0,
      pinterestCtr: 0,
      totalBenchmarksCPM: 0,
      totalBenchmarksCPC: 0,
      totalBenchmarksCTR: 0,
      totalBenchmarksNCROAS: 0,
      totalBenchmarksNCPA: 0,
      totalBenchmarksBlendedROAS: 0,
      totalBenchmarksTotalSpendAvg: 0,
      totalBenchmarksNewCustomersAvg: 0,
      totalBenchmarksSize: 0,
      totalBenchmarksOrdersAvg: 0,
      totalBenchmarksNewCustomersTotalPriceAvg: 0,
      totalBenchmarksTotalPriceUSDAvg: 0,
      totalBenchmarksFBAdsSpendAvg: 0,
      totalBenchmarksFBAdsImpressionsAvg: 0,
      totalBenchmarksFBAdsClicksAvg: 0,
      benchmarksFacebookRoas: 0,
      benchmarksGoogleRoas: 0,
      totalBenchmarksCPCGoogle: 0,
      totalBenchmarksCPMGoogle: 0,
      totalBenchmarksCTRGoogle: 0,
      sources: {},
      totalFacebookEnq: 0,
      totalGoogleEnq: 0,
      totalSnapchatEnq: 0,
      totalTiktokEnq: 0,
      totalPinterestEnq: 0,
      totalInstagramEnq: 0,
      responsesPrecent: 0,
      totalFacebookKno: -9.999999999999988,
      totalGoogleKno: -100,
      totalSnapchatKno: 100,
      totalTiktokKno: 100,
      totalPinterestKno: 0,
      totalInstagramKno: -39.99999999999999,
      responsesPrecentKno: 45.83333333333336,
      rechargeNewSub: 0,
      rechargeTotalNewSubscriptions: 0,
      rechargeCanceledSub: 0,
      rechargeExpiredSub: 0,
      rechargeTotalActiveSubsribers: 0,
      rechargeTotalNetSales: 0,
      rechargeItemsCount: 0,
      rechargeTransactionCount: 0,
      rechargeChurnRate: 0,
      rechargeMRR: 0,
      rechargeTotalActiveCustomers: 0,
      rechargeTotalChurnedCustomers: 0,
      facebookLikes: 0,
      facebookComments: 0,
      facebookShares: 0,
      facebookPosts: 0,
      facebookFollowers: 0,
      facebookSocialImpressions: 0,
      facebookSocialAvg: 0,
      facebookReach: 0,
      facebookProfileView: 0,
      facebookWebsiteClicks: 0,
      instagramLikes: 0,
      instagramComments: 0,
      instagramShares: 0,
      instagramPosts: 0,
      instagramFollowers: 0,
      instagramImpressions: 0,
      instagramAvg: 0,
      instagramAvgImpressionsFollowers: 0,
      instagramReach: 0,
      instagramProfileView: 0,
      instagramWebsiteClicks: 0,
      influencerConversionValue: -100,
      influencerSpend: 0,
      influencerRoas: 0,
      influencerPurchases: -100,
      influencerNcPurchases: 0,
      influencerNcConversionValue: 0,
      totalCustomAdSpends: 0,
      totalAmazonSales: 0,
      totalAmazonProductItemPrice: 0,
      totalAmazonSalesTaxes: 0,
      totalAmazonOrders: 0,
      totalAmazonItems: 0,
      totalAmazonFees: 0,
      totalAmazonSalesAFN: 0,
      totalAmazonProductItemPriceAFN: 0,
      totalAmazonSalesTaxesAFN: 0,
      totalAmazonOrdersAFN: 0,
      totalAmazonItemsAFN: 0,
      totalAmazonFeesAFN: 0,
      totalAmazonSalesMFN: 0,
      totalAmazonProductItemPriceMFN: 0,
      totalAmazonSalesTaxesMFN: 0,
      totalAmazonOrdersMFN: 0,
      totalAmazonItemsMFN: 0,
      totalAmazonFeesMFN: 0,
      totalCanceledAmazonSales: 0,
      totalCanceledAmazonProductItemPrice: 0,
      totalCanceledAmazonSalesTaxes: 0,
      totalCanceledAmazonOrders: 0,
      totalCanceledAmazonItems: 0,
      totalCanceledAmazonFees: 0,
      totalCanceledAmazonSalesAFN: 0,
      totalCanceledAmazonProductItemPriceAFN: 0,
      totalCanceledAmazonSalesTaxesAFN: 0,
      totalCanceledAmazonOrdersAFN: 0,
      totalCanceledAmazonItemsAFN: 0,
      totalCanceledAmazonFeesAFN: 0,
      totalCanceledAmazonSalesMFN: 0,
      totalCanceledAmazonProductItemPriceMFN: 0,
      totalCanceledAmazonSalesTaxesMFN: 0,
      totalCanceledAmazonOrdersMFN: 0,
      totalCanceledAmazonItemsMFN: 0,
      totalCanceledAmazonFeesMFN: 0,
      amazonAds: 0,
      amazonROAS: 0,
      amazonCPC: 0,
      amazonClicks: 0,
      amazonPurchases: 0,
      amazonTACos: 0,
      amazonAdsConversionValue: 0,
      amazonNetSales: 0,
      amazonNetProfit: 0,
      amazonMER: 0,
      amazonAOV: 0,
      amazonCPA: 0,
      amazonExpenses: 0,
      blendedSales: 5.087931860355596,
      pixelPurchases: 0,
      pixelUniqueAtc: 0,
      pixelUniqueVisitors: 0,
      pixelConversionRate: 0,
      twitter_spend: 0,
      twitterRoas: 0,
      twitterImpressions: 0,
      twitterCpm: 0,
      twitterCpa: 0,
      twitterPurchases: 0,
      twitterConversionValue: 0,
      twitterEngagements: 0,
      twitterFollows: 0,
      twitterClicks: 0,
      bingAdSpend: 0,
      bingImpressions: 0,
      bingClicks: 0,
      bingRoas: 0,
      bingConversions: 0,
      bingConversionValue: 0,
      bingCtr: 0,
      bingCpm: 0,
      bingCpa: 0,
      cashTotal: 0,
      creditTotal: 0,
      moneyInSum: 0,
      moneyOutSum: 0,
      beginningCash: 0,
      endingCash: 0,
      totalChange: 0,
      invoicesTotal: 0,
      invoices30Total: 0,
      invoices60Total: 0,
      invoices90Total: 0,
      ebitda: 0,
      burnRate: 0,
      runway: 0,
      valuation: 0,
      salesPerDay: 5.087931860355596,
      invoicesTotalNegative: 0,
      order_tags: {},
      customMetrics: {
        "6L38bwHBRvWKGMklbEpT": -14.537216153833628,
        I41lKG4ACkBr3f3ST4N2: 10.251658626982215,
        OPRT7ak1z1YyzrgPSWWx: -11.082238257176662,
        QhG75Cv0JLXxCZIkW3SM: 8.761338945099697,
        X7ANuQQK846E0PqFxxFe: -38.92577136225481,
        XDlpY3ObEXkBNtESCGTZ: 19.53843250384192,
        j9lMsp6olUZohex2yXKt: 22.96338491560799,
        nmNtVOCg6TvqSGhrUoOi: 15.608267694051374,
        ttwm1nDHQ4iluWhgah0m: -19.566426614669055,
        uBcU247PLBecmLdSUV4w: -8.048059622188855,
        uauOrxRIDEQBBJJkFHrW: 0,
      },
    },
  ],
  calculatedStats: [
    {
      totalSales: 2610.71,
      newCustomerSales: 1085.24,
      netSales: 2610.71,
      rcRevenue: 1525.47,
      totalPaymentGatewayCosts: 57.260000000000005,
      totalProductCosts: 506.72,
      totalHandlingFees: 0,
      totalCustomSpends: 0,
      totalInventoryItems: 858545,
      totalInventoryItemsMissing: 1113195,
      totalInventoryCost: 636140.65,
      totalInventoryValue: -11826279.88,
      shopifyAov: 54.38979166666667,
      averageGaRevenuePerTransaction: 54.38979166666667,
      fb_ads_spend: 1044.08,
      ga_adCost: 64.67685900000001,
      googleAllCpa: 64.67685900000001,
      googleBounceRate: 70.38183694530444,
      googleConversionValue: 79.97,
      totalSnapchatSpend: 0,
      totalSnapchatRoas: 0,
      snapchatImpressions: 0,
      snapchat_swipes: 0,
      snapchatCpm: 0,
      snapchatCpa: 0,
      totalSnapchatConversionPurchasesValue: 0,
      averageGaTransactionsPerSession: 4.953560371517028,
      totalGoogleAnalyticsSessions: 969,
      totalOrders: 48,
      totalNetProfit: 407.28314099999994,
      cashTurnover: 914.0031409999999,
      totalNetMargin: 15.600474238808602,
      totalCpa: 23.099101229166664,
      totalRevenuePerSession: 2.694231166150671,
      totalRefunds: 0,
      fb_ads_purchase_roas: 1.2920753198988586,
      ga_ROAS: 1.2364546027196526,
      totalGoogleAdsCtr: 0.825847580411475,
      totalGoogleAdsCpm: 9.370741669081427,
      googleCpc: 1.1346817368421054,
      totalGoogleAdsClicks: 57,
      totalGoogleAdsImpressions: 6902,
      ga_transactions_adGroup: 4,
      ga_all_transactionsRevenue_adGroup: 371.30000000000007,
      ga_all_transactions_adGroup: 1,
      totalAllRoas: 5.74084774277613,
      googleCpa: 16.169214750000002,
      averageFacebookCpc: 1.0990315789473684,
      facebookViewThrough: 0,
      facebookViewThroughRoas: 0,
      facebookViewThroughCpa: 0,
      averageFacebookCpm: 25.06313313169139,
      facebookCtr: 2.280474338662442,
      facebookCostPerOutboundClick: 2.4682742316784867,
      facebookConversionValue: 1349.0300000000002,
      facebookWebConversionValue: 1349.0300000000002,
      facebookMetaConversionValue: 0,
      facebookRevenuePerClick: 3.18919621749409,
      facebookCpa: 52.20399999999999,
      facebookPurchases: 20,
      facebookMetaPurchases: 0,
      facebookWebPurchases: 20,
      newCustomersCpa: 69.29730368749999,
      totalKlaviyoPlacedOrderSalesPercent: 8.916348426290167,
      totalKlaviyoPlacedOrderSalesPercentFlows: 8.916348426290167,
      totalKlaviyoPlacedOrderSalesPercentCampaigns: 0,
      klaviyoEmailOpenRate: 100,
      totalKlaviyoUnsubscribed: 3,
      totalKlaviyoPlacedOrderTotalPriceFlows: 232.78,
      totalKlaviyoPlacedOrderTotalPriceCampaigns: 0,
      totalKlaviyoSubscribedToList: 10,
      totalKlaviyoClickedEmail: 17,
      totalKlaviyoReceivedEmail: 484,
      totalKlaviyoClickedSms: 0,
      klaviyoCVR: 0.09917355371900827,
      klaviyoRevenuePerEmail: 5.394028925619835,
      totalKlaviyoNetNewSubscribers: 7,
      klaviyoPlacedOrderSales: 232.78,
      attentivePlacedOrderSales: 0,
      totalAttentivePlacedOrder: 0,
      totalAttentiveNewSubscribed: 0,
      totalAttentiveNetNewsubscribers: 0,
      totalAttentiveUnsubscribed: 0,
      totalAttentivePlacedOrderTotalPriceFlows: 0,
      totalAttentivePlacedOrderSalesPercentFlows: 0,
      totalAttentivePlacedOrderTotalPriceCampaigns: 0,
      totalAttentivePlacedOrderSalesPercentCampaigns: 0,
      tiktok_spend: 0,
      tiktok_complete_payment_roas: 0,
      tiktokImpressions: 0,
      averageTiktokCpm: 0,
      averageTiktokCpc: 0,
      tiktokCtr: 0,
      tiktokCpa: 0,
      tiktokConversionValue: 0,
      tiktokPurchases: 0,
      uniqueCustomerLifetimeValue: 54.38979166666667,
      customerFrequency: 1,
      ltvCpa: 2.3546280492502465,
      mer: 42.46955268873218,
      totalReturns: 0,
      totalTaxes: 146.69,
      newCustomersPercent: 33.333333333333336,
      oldCustomersPercent: 66.66666666666666,
      newCustomersOrders: 16,
      getUniqueCustomerCount: 48,
      totalShippingCosts: 384,
      totalGoogleAnalyticsUsers: 966,
      totalGorgiasTicketsCreated: 0,
      totalGorgiasTicketsReplied: 0,
      averageGorgiasResponseTime: 0,
      averageGorgiasResolutionTime: 0,
      totalVariantsSold: 82,
      blendedAds: 1108.7568589999998,
      totalRoas: 2.35,
      newCustomersRoas: "0.98",
      blendedAttributedRoas: "1.29",
      poas: 1.3673331422430461,
      shopifyCpa: 23.099101229166664,
      pinterestSpend: 0,
      pinterestRoas: 0,
      pinterestCpc: 0,
      pinterestCpm: 0,
      pinterestConversionValue: 0,
      pinterestPurchases: 0,
      pinterestImpressions: 0,
      pinterestCtr: 0,
      totalBenchmarksCPM: 0,
      totalBenchmarksCPC: 0,
      totalBenchmarksCTR: 0,
      totalBenchmarksNCROAS: 0,
      totalBenchmarksNCPA: 0,
      totalBenchmarksBlendedROAS: 0,
      totalBenchmarksTotalSpendAvg: 0,
      totalBenchmarksNewCustomersAvg: 0,
      totalBenchmarksSize: 0,
      totalBenchmarksOrdersAvg: 0,
      totalBenchmarksNewCustomersTotalPriceAvg: 0,
      totalBenchmarksTotalPriceUSDAvg: 0,
      totalBenchmarksFBAdsSpendAvg: 0,
      totalBenchmarksFBAdsImpressionsAvg: 0,
      totalBenchmarksFBAdsClicksAvg: 0,
      benchmarksFacebookRoas: 0,
      benchmarksGoogleRoas: 0,
      totalBenchmarksCPCGoogle: 0,
      totalBenchmarksCPMGoogle: 0,
      totalBenchmarksCTRGoogle: 0,
      sources: {},
      totalFacebookEnq: 0,
      totalGoogleEnq: 0,
      totalSnapchatEnq: 0,
      totalTiktokEnq: 0,
      totalPinterestEnq: 0,
      totalInstagramEnq: 0,
      responsesPrecent: 0,
      totalFacebookKno: 60,
      totalGoogleKno: 0,
      totalSnapchatKno: 10,
      totalTiktokKno: 10,
      totalPinterestKno: 0,
      totalInstagramKno: 10,
      responsesPrecentKno: 20.833333333333336,
      rechargeNewSub: 0,
      rechargeTotalNewSubscriptions: 0,
      rechargeCanceledSub: 0,
      rechargeExpiredSub: 0,
      rechargeTotalActiveSubsribers: 0,
      rechargeTotalNetSales: 0,
      rechargeItemsCount: 0,
      rechargeTransactionCount: 0,
      rechargeChurnRate: 0,
      rechargeMRR: 0,
      rechargeTotalActiveCustomers: 0,
      rechargeTotalChurnedCustomers: 0,
      facebookLikes: 0,
      facebookComments: 0,
      facebookShares: 0,
      facebookPosts: 0,
      facebookFollowers: 0,
      facebookSocialImpressions: 0,
      facebookSocialAvg: 0,
      facebookReach: 0,
      facebookProfileView: 0,
      facebookWebsiteClicks: 0,
      instagramLikes: 0,
      instagramComments: 0,
      instagramShares: 0,
      instagramPosts: 0,
      instagramFollowers: 0,
      instagramImpressions: 0,
      instagramAvg: 0,
      instagramAvgImpressionsFollowers: 0,
      instagramReach: 0,
      instagramProfileView: 0,
      instagramWebsiteClicks: 0,
      influencerConversionValue: 0,
      influencerSpend: 0,
      influencerRoas: 0,
      influencerPurchases: 0,
      influencerNcPurchases: 0,
      influencerNcConversionValue: 0,
      totalCustomAdSpends: 0,
      totalAmazonSales: 0,
      totalAmazonProductItemPrice: 0,
      totalAmazonSalesTaxes: 0,
      totalAmazonOrders: 0,
      totalAmazonItems: 0,
      totalAmazonFees: 0,
      totalAmazonSalesAFN: 0,
      totalAmazonProductItemPriceAFN: 0,
      totalAmazonSalesTaxesAFN: 0,
      totalAmazonOrdersAFN: 0,
      totalAmazonItemsAFN: 0,
      totalAmazonFeesAFN: 0,
      totalAmazonSalesMFN: 0,
      totalAmazonProductItemPriceMFN: 0,
      totalAmazonSalesTaxesMFN: 0,
      totalAmazonOrdersMFN: 0,
      totalAmazonItemsMFN: 0,
      totalAmazonFeesMFN: 0,
      totalCanceledAmazonSales: 0,
      totalCanceledAmazonProductItemPrice: 0,
      totalCanceledAmazonSalesTaxes: 0,
      totalCanceledAmazonOrders: 0,
      totalCanceledAmazonItems: 0,
      totalCanceledAmazonFees: 0,
      totalCanceledAmazonSalesAFN: 0,
      totalCanceledAmazonProductItemPriceAFN: 0,
      totalCanceledAmazonSalesTaxesAFN: 0,
      totalCanceledAmazonOrdersAFN: 0,
      totalCanceledAmazonItemsAFN: 0,
      totalCanceledAmazonFeesAFN: 0,
      totalCanceledAmazonSalesMFN: 0,
      totalCanceledAmazonProductItemPriceMFN: 0,
      totalCanceledAmazonSalesTaxesMFN: 0,
      totalCanceledAmazonOrdersMFN: 0,
      totalCanceledAmazonItemsMFN: 0,
      totalCanceledAmazonFeesMFN: 0,
      amazonAds: 0,
      amazonROAS: 0,
      amazonCPC: 0,
      amazonClicks: 0,
      amazonPurchases: 0,
      amazonTACos: 0,
      amazonAdsConversionValue: 0,
      amazonNetSales: 0,
      amazonNetProfit: 0,
      amazonMER: 0,
      amazonAOV: 0,
      amazonCPA: 0,
      amazonExpenses: 0,
      blendedSales: 2610.71,
      pixelPurchases: 0,
      pixelUniqueAtc: 0,
      pixelUniqueVisitors: 0,
      pixelConversionRate: 0,
      twitter_spend: 0,
      twitterRoas: 0,
      twitterImpressions: 0,
      twitterCpm: 0,
      twitterCpa: 0,
      twitterPurchases: 0,
      twitterConversionValue: 0,
      twitterEngagements: 0,
      twitterFollows: 0,
      twitterClicks: 0,
      bingAdSpend: 0,
      bingImpressions: 0,
      bingClicks: 0,
      bingRoas: 0,
      bingConversions: 0,
      bingConversionValue: 0,
      bingCtr: 0,
      bingCpm: 0,
      bingCpa: 0,
      cashTotal: 0,
      creditTotal: 0,
      moneyInSum: 0,
      moneyOutSum: 0,
      beginningCash: 0,
      endingCash: 0,
      totalChange: 0,
      invoicesTotal: 0,
      invoices30Total: 0,
      invoices60Total: 0,
      invoices90Total: 0,
      ebitda: 0,
      burnRate: 0,
      runway: 0,
      valuation: 0,
      salesPerDay: 2610.71,
      invoicesTotalNegative: 0,
      order_tags: {},
      customMetrics: {
        "6L38bwHBRvWKGMklbEpT": 2.3546280492502465,
        I41lKG4ACkBr3f3ST4N2: 18.556666666666665,
        OPRT7ak1z1YyzrgPSWWx: 87.85397035416665,
        QhG75Cv0JLXxCZIkW3SM: 41.65576789583333,
        X7ANuQQK846E0PqFxxFe: 12.734023770833339,
        XDlpY3ObEXkBNtESCGTZ: 10.556666666666667,
        j9lMsp6olUZohex2yXKt: 1108.7568589999998,
        nmNtVOCg6TvqSGhrUoOi: -33.46417868749998,
        ttwm1nDHQ4iluWhgah0m: 67.91135761374998,
        uBcU247PLBecmLdSUV4w: 54.38979166666667,
        uauOrxRIDEQBBJJkFHrW: 8,
      },
    },
    {
      totalSales: 2484.31,
      newCustomerSales: 930.96,
      netSales: 2484.31,
      rcRevenue: 1553.35,
      totalPaymentGatewayCosts: 37.019999999999996,
      totalProductCosts: 370.90999999999997,
      totalHandlingFees: 0,
      totalCustomSpends: 0,
      totalInventoryItems: 858545,
      totalInventoryItemsMissing: 1113195,
      totalInventoryCost: 636140.65,
      totalInventoryValue: -11826279.88,
      shopifyAov: 59.150238095238095,
      averageGaRevenuePerTransaction: 59.150238095238095,
      fb_ads_spend: 849.09,
      ga_adCost: 52.606761000000006,
      googleAllCpa: 0,
      googleBounceRate: 72.25647348951911,
      googleConversionValue: 0,
      totalSnapchatSpend: 0,
      totalSnapchatRoas: 0,
      snapchatImpressions: 0,
      snapchat_swipes: 0,
      snapchatCpm: 0,
      snapchatCpa: 0,
      totalSnapchatConversionPurchasesValue: 0,
      averageGaTransactionsPerSession: 5.178791615289765,
      totalGoogleAnalyticsSessions: 811,
      totalOrders: 42,
      totalNetProfit: 716.883239,
      cashTurnover: 1087.7932389999999,
      totalNetMargin: 28.85643253056182,
      totalCpa: 21.4689705,
      totalRevenuePerSession: 3.0632675709001234,
      totalRefunds: 0,
      fb_ads_purchase_roas: 0.653817616507084,
      ga_ROAS: 0,
      totalGoogleAdsCtr: 0.7498197548666186,
      totalGoogleAdsCpm: 7.585690122566692,
      googleCpc: 1.0116684807692309,
      totalGoogleAdsClicks: 52,
      totalGoogleAdsImpressions: 6935,
      ga_transactions_adGroup: 0,
      ga_all_transactionsRevenue_adGroup: 0,
      ga_all_transactions_adGroup: 0,
      totalAllRoas: 0,
      googleCpa: 0,
      averageFacebookCpc: 1.2672985074626866,
      facebookViewThrough: 0,
      facebookViewThroughRoas: 0,
      facebookViewThroughCpa: 0,
      averageFacebookCpm: 26.89973071439886,
      facebookCtr: 2.1226041501663238,
      facebookCostPerOutboundClick: 2.6369254658385093,
      facebookConversionValue: 555.15,
      facebookWebConversionValue: 555.15,
      facebookMetaConversionValue: 0,
      facebookRevenuePerClick: 1.7240683229813665,
      facebookCpa: 121.29857142857144,
      facebookPurchases: 7,
      facebookMetaPurchases: 0,
      facebookWebPurchases: 7,
      newCustomersCpa: 81.97243281818182,
      totalKlaviyoPlacedOrderSalesPercent: 8.066223619435577,
      totalKlaviyoPlacedOrderSalesPercentFlows: 8.066223619435577,
      totalKlaviyoPlacedOrderSalesPercentCampaigns: 0,
      klaviyoEmailOpenRate: 100,
      totalKlaviyoUnsubscribed: 1,
      totalKlaviyoPlacedOrderTotalPriceFlows: 200.39,
      totalKlaviyoPlacedOrderTotalPriceCampaigns: 0,
      totalKlaviyoSubscribedToList: 6,
      totalKlaviyoClickedEmail: 13,
      totalKlaviyoReceivedEmail: 552,
      totalKlaviyoClickedSms: 0,
      klaviyoCVR: 0.07608695652173914,
      klaviyoRevenuePerEmail: 4.500561594202899,
      totalKlaviyoNetNewSubscribers: 5,
      klaviyoPlacedOrderSales: 200.39,
      attentivePlacedOrderSales: 0,
      totalAttentivePlacedOrder: 0,
      totalAttentiveNewSubscribed: 0,
      totalAttentiveNetNewsubscribers: 0,
      totalAttentiveUnsubscribed: 0,
      totalAttentivePlacedOrderTotalPriceFlows: 0,
      totalAttentivePlacedOrderSalesPercentFlows: 0,
      totalAttentivePlacedOrderTotalPriceCampaigns: 0,
      totalAttentivePlacedOrderSalesPercentCampaigns: 0,
      tiktok_spend: 0,
      tiktok_complete_payment_roas: 0,
      tiktokImpressions: 0,
      averageTiktokCpm: 0,
      averageTiktokCpc: 0,
      tiktokCtr: 0,
      tiktokCpa: 0,
      tiktokConversionValue: 0,
      tiktokPurchases: 0,
      uniqueCustomerLifetimeValue: 7.350029585798817,
      customerFrequency: 0.1242603550295858,
      ltvCpa: 0.34235594043965994,
      mer: 36.29566201480492,
      totalReturns: 0,
      totalTaxes: 121.80000000000001,
      newCustomersPercent: 26.19047619047619,
      oldCustomersPercent: 73.80952380952381,
      newCustomersOrders: 11,
      getUniqueCustomerCount: 338,
      totalShippingCosts: 336,
      totalGoogleAnalyticsUsers: 806,
      totalGorgiasTicketsCreated: 0,
      totalGorgiasTicketsReplied: 0,
      averageGorgiasResponseTime: 0,
      averageGorgiasResolutionTime: 0,
      totalVariantsSold: 79,
      blendedAds: 901.696761,
      totalRoas: 2.76,
      newCustomersRoas: "1.03",
      blendedAttributedRoas: "0.62",
      poas: 1.7950380549276477,
      shopifyCpa: 21.4689705,
      pinterestSpend: 0,
      pinterestRoas: 0,
      pinterestCpc: 0,
      pinterestCpm: 0,
      pinterestConversionValue: 0,
      pinterestPurchases: 0,
      pinterestImpressions: 0,
      pinterestCtr: 0,
      totalBenchmarksCPM: 0,
      totalBenchmarksCPC: 0,
      totalBenchmarksCTR: 0,
      totalBenchmarksNCROAS: 0,
      totalBenchmarksNCPA: 0,
      totalBenchmarksBlendedROAS: 0,
      totalBenchmarksTotalSpendAvg: 0,
      totalBenchmarksNewCustomersAvg: 0,
      totalBenchmarksSize: 0,
      totalBenchmarksOrdersAvg: 0,
      totalBenchmarksNewCustomersTotalPriceAvg: 0,
      totalBenchmarksTotalPriceUSDAvg: 0,
      totalBenchmarksFBAdsSpendAvg: 0,
      totalBenchmarksFBAdsImpressionsAvg: 0,
      totalBenchmarksFBAdsClicksAvg: 0,
      benchmarksFacebookRoas: 0,
      benchmarksGoogleRoas: 0,
      totalBenchmarksCPCGoogle: 0,
      totalBenchmarksCPMGoogle: 0,
      totalBenchmarksCTRGoogle: 0,
      sources: {},
      totalFacebookEnq: 0,
      totalGoogleEnq: 0,
      totalSnapchatEnq: 0,
      totalTiktokEnq: 0,
      totalPinterestEnq: 0,
      totalInstagramEnq: 0,
      responsesPrecent: 0,
      totalFacebookKno: 66.66666666666666,
      totalGoogleKno: 16.666666666666664,
      totalSnapchatKno: 0,
      totalTiktokKno: 0,
      totalPinterestKno: 0,
      totalInstagramKno: 16.666666666666664,
      responsesPrecentKno: 14.285714285714285,
      rechargeNewSub: 0,
      rechargeTotalNewSubscriptions: 0,
      rechargeCanceledSub: 0,
      rechargeExpiredSub: 0,
      rechargeTotalActiveSubsribers: 0,
      rechargeTotalNetSales: 0,
      rechargeItemsCount: 0,
      rechargeTransactionCount: 0,
      rechargeChurnRate: 0,
      rechargeMRR: 0,
      rechargeTotalActiveCustomers: 0,
      rechargeTotalChurnedCustomers: 0,
      facebookLikes: 0,
      facebookComments: 0,
      facebookShares: 0,
      facebookPosts: 0,
      facebookFollowers: 0,
      facebookSocialImpressions: 0,
      facebookSocialAvg: 0,
      facebookReach: 0,
      facebookProfileView: 0,
      facebookWebsiteClicks: 0,
      instagramLikes: 0,
      instagramComments: 0,
      instagramShares: 0,
      instagramPosts: 0,
      instagramFollowers: 0,
      instagramImpressions: 0,
      instagramAvg: 0,
      instagramAvgImpressionsFollowers: 0,
      instagramReach: 0,
      instagramProfileView: 0,
      instagramWebsiteClicks: 0,
      influencerConversionValue: 28.40999984741211,
      influencerSpend: 0,
      influencerRoas: 0,
      influencerPurchases: 1,
      influencerNcPurchases: 0,
      influencerNcConversionValue: 0,
      totalCustomAdSpends: 0,
      totalAmazonSales: 0,
      totalAmazonProductItemPrice: 0,
      totalAmazonSalesTaxes: 0,
      totalAmazonOrders: 0,
      totalAmazonItems: 0,
      totalAmazonFees: 0,
      totalAmazonSalesAFN: 0,
      totalAmazonProductItemPriceAFN: 0,
      totalAmazonSalesTaxesAFN: 0,
      totalAmazonOrdersAFN: 0,
      totalAmazonItemsAFN: 0,
      totalAmazonFeesAFN: 0,
      totalAmazonSalesMFN: 0,
      totalAmazonProductItemPriceMFN: 0,
      totalAmazonSalesTaxesMFN: 0,
      totalAmazonOrdersMFN: 0,
      totalAmazonItemsMFN: 0,
      totalAmazonFeesMFN: 0,
      totalCanceledAmazonSales: 0,
      totalCanceledAmazonProductItemPrice: 0,
      totalCanceledAmazonSalesTaxes: 0,
      totalCanceledAmazonOrders: 0,
      totalCanceledAmazonItems: 0,
      totalCanceledAmazonFees: 0,
      totalCanceledAmazonSalesAFN: 0,
      totalCanceledAmazonProductItemPriceAFN: 0,
      totalCanceledAmazonSalesTaxesAFN: 0,
      totalCanceledAmazonOrdersAFN: 0,
      totalCanceledAmazonItemsAFN: 0,
      totalCanceledAmazonFeesAFN: 0,
      totalCanceledAmazonSalesMFN: 0,
      totalCanceledAmazonProductItemPriceMFN: 0,
      totalCanceledAmazonSalesTaxesMFN: 0,
      totalCanceledAmazonOrdersMFN: 0,
      totalCanceledAmazonItemsMFN: 0,
      totalCanceledAmazonFeesMFN: 0,
      amazonAds: 0,
      amazonROAS: 0,
      amazonCPC: 0,
      amazonClicks: 0,
      amazonPurchases: 0,
      amazonTACos: 0,
      amazonAdsConversionValue: 0,
      amazonNetSales: 0,
      amazonNetProfit: 0,
      amazonMER: 0,
      amazonAOV: 0,
      amazonCPA: 0,
      amazonExpenses: 0,
      blendedSales: 2484.31,
      pixelPurchases: 0,
      pixelUniqueAtc: 0,
      pixelUniqueVisitors: 0,
      pixelConversionRate: 0,
      twitter_spend: 0,
      twitterRoas: 0,
      twitterImpressions: 0,
      twitterCpm: 0,
      twitterCpa: 0,
      twitterPurchases: 0,
      twitterConversionValue: 0,
      twitterEngagements: 0,
      twitterFollows: 0,
      twitterClicks: 0,
      bingAdSpend: 0,
      bingImpressions: 0,
      bingClicks: 0,
      bingRoas: 0,
      bingConversions: 0,
      bingConversionValue: 0,
      bingCtr: 0,
      bingCpm: 0,
      bingCpa: 0,
      cashTotal: 0,
      creditTotal: 0,
      moneyInSum: 0,
      moneyOutSum: 0,
      beginningCash: 0,
      endingCash: 0,
      totalChange: 0,
      invoicesTotal: 0,
      invoices30Total: 0,
      invoices60Total: 0,
      invoices90Total: 0,
      ebitda: 0,
      burnRate: 0,
      runway: 0,
      valuation: 0,
      salesPerDay: 2484.31,
      invoicesTotalNegative: 0,
      order_tags: {},
      customMetrics: {
        "6L38bwHBRvWKGMklbEpT": 2.7551501873477395,
        I41lKG4ACkBr3f3ST4N2: 16.831190476190475,
        OPRT7ak1z1YyzrgPSWWx: 98.80362329437229,
        QhG75Cv0JLXxCZIkW3SM: 38.300160976190476,
        X7ANuQQK846E0PqFxxFe: 20.85007711904762,
        XDlpY3ObEXkBNtESCGTZ: 8.831190476190475,
        j9lMsp6olUZohex2yXKt: 901.696761,
        nmNtVOCg6TvqSGhrUoOi: -39.65338519913419,
        ttwm1nDHQ4iluWhgah0m: 84.43160580272728,
        uBcU247PLBecmLdSUV4w: 59.150238095238095,
        uauOrxRIDEQBBJJkFHrW: 8,
      },
    },
  ],
  previousPeriodRawStats: {
    stats: [
      {
        start: "2023-06-11T00:00:00-04:00",
        end: "2023-06-11T23:59:59-04:00",
        hours: {
          "0": {
            ga_transactions: 30,
            ga_transactionRevenue: 1668.95,
            ga_users: 189,
            ga_bounces: 140,
            ga_sessions: 192,
          },
          "1": {
            ga_transactions: 2,
            ga_transactionRevenue: 88.21,
            ga_users: 155,
            ga_bounces: 113,
            ga_sessions: 152,
          },
          "2": {
            ga_transactions: 1,
            ga_transactionRevenue: 137.61,
            ga_users: 103,
            ga_bounces: 83,
            ga_sessions: 105,
          },
          "3": {
            ga_transactions: 1,
            ga_transactionRevenue: 37.85,
            ga_users: 74,
            ga_bounces: 50,
            ga_sessions: 76,
          },
          "4": {
            ga_transactions: 3,
            ga_transactionRevenue: 128.83,
            ga_users: 53,
            ga_bounces: 33,
            ga_sessions: 56,
          },
          "5": {
            ga_transactions: 2,
            ga_transactionRevenue: 170.4,
            ga_users: 105,
            ga_bounces: 80,
            ga_sessions: 105,
          },
          "6": {
            ga_transactions: 3,
            ga_transactionRevenue: 252.46,
            ga_users: 127,
            ga_bounces: 87,
            ga_sessions: 125,
          },
        },
        id: "June 11, 2023",
      },
    ],
    ltv: {
      uniqueCustomerCount: 338,
    },
    totalInventoryItems: 858545,
    totalInventoryItemsMissing: 1113195,
    totalInventoryCost: 636140.65,
    totalInventoryValue: -11826279.88,
    newStats: {
      "facebook-ads": [
        {
          hours: {
            "0": {
              spend: 163.38,
              conversionValue: 105.99,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 101,
              impressions: 5985,
              outboundClicks: 40,
              purchases: 1,
              metaPurchases: 0,
              totalVideoView: 2561,
              threeSecondVideoView: 23,
            },
            "1": {
              spend: 165.89999999999995,
              conversionValue: 59.8,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 140,
              impressions: 6522,
              outboundClicks: 77,
              purchases: 1,
              metaPurchases: 0,
              totalVideoView: 3600,
              threeSecondVideoView: 31,
            },
            "2": {
              spend: 142.35,
              conversionValue: 111.14999999999999,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 114,
              impressions: 5695,
              outboundClicks: 69,
              purchases: 2,
              metaPurchases: 0,
              totalVideoView: 3326,
              threeSecondVideoView: 30,
            },
            "3": {
              spend: 76.10999999999999,
              conversionValue: 99.99,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 57,
              impressions: 2661,
              outboundClicks: 31,
              purchases: 1,
              metaPurchases: 0,
              totalVideoView: 1636,
              threeSecondVideoView: 16,
            },
            "4": {
              spend: 61.890000000000015,
              conversionValue: 29.989999999999995,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 45,
              impressions: 2109,
              outboundClicks: 18,
              purchases: 1,
              metaPurchases: 0,
              totalVideoView: 1354,
              threeSecondVideoView: 10,
            },
            "5": {
              spend: 93.7,
              conversionValue: 148.23,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 78,
              impressions: 3361,
              outboundClicks: 34,
              purchases: 1,
              metaPurchases: 0,
              totalVideoView: 1794,
              threeSecondVideoView: 8,
            },
            "6": {
              spend: 145.76,
              conversionValue: 0,
              metaConversionValue: 0,
              oneDayViewConversionValue: 0,
              oneDayViewPurchasesValue: 0,
              clicks: 135,
              impressions: 5232,
              outboundClicks: 53,
              purchases: 0,
              metaPurchases: 0,
              totalVideoView: 3027,
              threeSecondVideoView: 10,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      "google-ads": [
        {
          hours: {
            "1": {
              spend: 18.197717,
              conversionValue: 0,
              clicks: 16,
              impressions: 3040,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0,
            },
            "2": {
              spend: 8.654917000000001,
              conversionValue: 0,
              clicks: 12,
              impressions: 1305,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0,
            },
            "3": {
              spend: 28.58151,
              conversionValue: 0,
              clicks: 28,
              impressions: 1011,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0,
            },
            "4": {
              spend: -13.118663999999999,
              conversionValue: 0,
              clicks: -14,
              impressions: 468,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0.16666666666666666,
            },
            "5": {
              spend: 7.3968539999999985,
              conversionValue: 0,
              clicks: 7,
              impressions: 617,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0.11904761904761904,
            },
            "6": {
              spend: 2.8944270000000003,
              conversionValue: 0,
              clicks: 3,
              impressions: 494,
              purchases: 0,
              allConversions: 0,
              allConversionValue: 0,
              threeSecondVideoView: 0,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      "snapchat-ads": [],
      klaviyo: [
        {
          hours: {
            "0": {
              unsubscribed: 0,
              subscribedToList: 2,
              openedEmail: 450,
              receivedEmail: 107,
              clickedSms: 0,
              clickedEmail: 2,
              conversionValue: 1668.95,
              flowsConversionValue: 29.99,
              flowsCount: 1,
              campaignsConversionValue: 0,
            },
            "1": {
              unsubscribed: 0,
              subscribedToList: 1,
              openedEmail: 428,
              receivedEmail: 54,
              clickedSms: 0,
              clickedEmail: 2,
              conversionValue: 88.21,
              flowsConversionValue: 0,
              flowsCount: 0,
              campaignsConversionValue: 0,
            },
            "2": {
              unsubscribed: 0,
              subscribedToList: 0,
              openedEmail: 362,
              receivedEmail: 287,
              clickedSms: 0,
              clickedEmail: 4,
              conversionValue: 137.61,
              flowsConversionValue: 0,
              flowsCount: 0,
              campaignsConversionValue: 0,
            },
            "3": {
              unsubscribed: 0,
              subscribedToList: 0,
              openedEmail: 334,
              receivedEmail: 32,
              clickedSms: 0,
              clickedEmail: 1,
              conversionValue: 0,
              flowsConversionValue: 0,
              flowsCount: 0,
              campaignsConversionValue: 0,
            },
            "4": {
              unsubscribed: 0,
              subscribedToList: 1,
              openedEmail: 295,
              receivedEmail: 12,
              clickedSms: 0,
              clickedEmail: 4,
              conversionValue: 166.68,
              flowsConversionValue: 0,
              flowsCount: 0,
              campaignsConversionValue: 0,
            },
            "5": {
              unsubscribed: 1,
              subscribedToList: 1,
              openedEmail: 270,
              receivedEmail: 22,
              clickedSms: 0,
              clickedEmail: 0,
              conversionValue: 170.4,
              flowsConversionValue: 170.39999999999998,
              flowsCount: 2,
              campaignsConversionValue: 0,
            },
            "6": {
              unsubscribed: 0,
              subscribedToList: 1,
              openedEmail: 238,
              receivedEmail: 38,
              clickedSms: 0,
              clickedEmail: 0,
              conversionValue: 207.48,
              flowsConversionValue: 0,
              flowsCount: 0,
              campaignsConversionValue: 0,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      enquirelabs: [],
      kno: [
        {
          hours: {
            "0": {
              "facebook-ads": {
                responses: 2,
                price: 212.5999984741211,
              },
              total: {
                responses: 2,
                price: 212.5999984741211,
              },
            },
            "1": {
              total: {
                responses: 0,
                price: 0,
              },
            },
            "2": {
              total: {
                responses: 0,
                price: 0,
              },
            },
            "3": {
              total: {
                responses: 0,
                price: 0,
              },
            },
            "4": {
              "instagram-ads": {
                responses: 1,
                price: 44.97999954223633,
              },
              "google-ads": {
                responses: 1,
                price: 37.849998474121094,
              },
              total: {
                responses: 2,
                price: 82.82999801635742,
              },
            },
            "5": {
              total: {
                responses: 0,
                price: 0,
              },
            },
            "6": {
              "facebook-ads": {
                responses: 2,
                price: 144.96999740600586,
              },
              total: {
                responses: 2,
                price: 144.96999740600586,
              },
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      "twitter-ads": [
        {
          hours: {
            "0": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "1": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "2": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "3": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "4": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "5": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
            "6": {
              spend: 0,
              conversionValue: 0,
              purchases: 0,
              clicks: 0,
              impressions: 0,
              threeSecondVideoView: 0,
              engagements: 0,
              follows: 0,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      influencers: [
        {
          hours: {
            "0": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
            "1": {
              pixelConversionValue: 28.40999984741211,
              spend: 0,
              pixelPurchases: 1,
              pixelCogs: 0,
              pixelProductCount: 1,
              roas: null,
              aov: 0,
              cpa: 0,
              cpc: 0,
              cpm: 0,
              ctr: 0,
              outboundCtr: 0,
              pixelRoas: 0,
              pixelNcRoas: 0,
              pixelCpa: 0,
              pixelAov: 28.40999984741211,
              pixelNcAov: 0,
              pixelNcCpa: 0,
              pixelProfit: 28.40999984741211,
              pixelConversionRate: 0,
              pixelNcConversionRate: 0,
              pixelCostPerAtc: 0,
              pixelCostPerEmailSignup: 0,
              pixelCostPerNewVisitor: 0,
              pixelCostPerVisitor: 0,
              pixelEmailSignupRate: 0,
              pixelAvgTimeOnSite: 0,
              pixelBounceRate: 0,
              pixelAvgTimeToConversion: 0,
              pixelAvgTouchpoints: 0,
              pixelNewVisitorPerc: 0,
              pixelNcPurchasesPerc: 0,
            },
            "2": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
            "3": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
            "4": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
            "5": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
            "6": {
              pixelConversionValue: 0,
              spend: 0,
              roas: null,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
      shopify: [
        {
          hours: {
            "0": {
              total_tax: 77.38,
              total_price: 1668.95,
              avg_price: 55.63166666666667,
              total_items: 50,
              total_refund: 0,
              total_cost: 223.29999999999998,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 240,
              total_payment_gateway_costs: 18.59,
              refund_count: 0,
              count: 30,
              new_customers_count: 3,
              new_customers_total_price: 250.03,
              new_customers_total_tax: 15.07,
              net_sales: 1668.95,
              total_percentage_cost: 9.5871,
              total_payment_gateway_fees: 9,
              total_discounts: 90,
              total_shipping_price: 24.96,
              orders_with_amount: 30,
              new_customers_avg_price: 83.34333333333333,
              new_customers_total_items: 6,
              total_items_cogs: 50,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "1": {
              total_tax: 7,
              total_price: 88.21,
              avg_price: 44.105,
              total_items: 3,
              total_refund: 0,
              total_cost: 10.82,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 16,
              total_payment_gateway_costs: 3.2399999999999998,
              refund_count: 0,
              count: 2,
              new_customers_count: 1,
              new_customers_total_price: 59.8,
              new_customers_total_tax: 4.83,
              net_sales: 88.21,
              total_percentage_cost: 2.6462999999999997,
              total_payment_gateway_fees: 0.6,
              total_discounts: 18.74,
              total_shipping_price: 4.99,
              orders_with_amount: 2,
              new_customers_avg_price: 59.8,
              new_customers_total_items: 2,
              total_items_cogs: 3,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "2": {
              total_tax: 9.64,
              total_price: 137.61,
              avg_price: 137.61,
              total_items: 4,
              total_refund: 0,
              total_cost: 15.92,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 8,
              total_payment_gateway_costs: 7.18,
              refund_count: 0,
              count: 1,
              new_customers_count: 1,
              new_customers_total_price: 137.61,
              new_customers_total_tax: 9.64,
              net_sales: 137.61,
              total_percentage_cost: 6.880500000000001,
              total_payment_gateway_fees: 0.3,
              total_discounts: 31.99,
              total_shipping_price: 0,
              orders_with_amount: 1,
              new_customers_avg_price: 137.61,
              new_customers_total_items: 4,
              total_items_cogs: 4,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "3": {
              total_tax: 2.87,
              total_price: 37.85,
              avg_price: 37.85,
              total_items: 1,
              total_refund: 0,
              total_cost: 4.77,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 8,
              total_payment_gateway_costs: 1.44,
              refund_count: 0,
              count: 1,
              new_customers_count: 1,
              new_customers_total_price: 37.85,
              new_customers_total_tax: 2.87,
              net_sales: 37.85,
              total_percentage_cost: 1.1355,
              total_payment_gateway_fees: 0.3,
              total_discounts: 0,
              total_shipping_price: 4.99,
              orders_with_amount: 1,
              new_customers_avg_price: 37.85,
              new_customers_total_items: 1,
              total_items_cogs: 1,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "4": {
              total_tax: 3.4,
              total_price: 128.82999999999998,
              avg_price: 42.94333333333333,
              total_items: 10,
              total_refund: 0,
              total_cost: 20.36,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 24,
              total_payment_gateway_costs: 2.8200000000000003,
              refund_count: 0,
              count: 3,
              new_customers_count: 1,
              new_customers_total_price: 44.98,
              new_customers_total_tax: 0,
              net_sales: 128.82999999999998,
              total_percentage_cost: 1.9190000000000003,
              total_payment_gateway_fees: 0.8999999999999999,
              total_discounts: 110.97,
              total_shipping_price: 29.96,
              orders_with_amount: 3,
              new_customers_avg_price: 44.98,
              new_customers_total_items: 1,
              total_items_cogs: 10,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "5": {
              total_tax: 14.01,
              total_price: 170.39999999999998,
              avg_price: 85.19999999999999,
              total_items: 3,
              total_refund: 0,
              total_cost: 45,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 16,
              total_payment_gateway_costs: 0.6,
              refund_count: 0,
              count: 2,
              new_customers_count: 1,
              new_customers_total_price: 148.23,
              new_customers_total_tax: 12.24,
              net_sales: 170.39999999999998,
              total_percentage_cost: 0,
              total_payment_gateway_fees: 0.6,
              total_discounts: 39.08,
              total_shipping_price: 0,
              orders_with_amount: 2,
              new_customers_avg_price: 148.23,
              new_customers_total_items: 2,
              total_items_cogs: 3,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
            "6": {
              total_tax: 7.5,
              total_price: 252.45999999999998,
              avg_price: 84.15333333333332,
              total_items: 8,
              total_refund: 0,
              total_cost: 50.74,
              total_fees: 0,
              total_handling_fees: 0,
              total_shipping_costs: 24,
              total_payment_gateway_costs: 3.15,
              refund_count: 0,
              count: 3,
              new_customers_count: 3,
              new_customers_total_price: 252.45999999999998,
              new_customers_total_tax: 7.5,
              net_sales: 252.45999999999998,
              total_percentage_cost: 2.249,
              total_payment_gateway_fees: 0.8999999999999999,
              total_discounts: 124.95,
              total_shipping_price: 4.99,
              orders_with_amount: 3,
              new_customers_avg_price: 84.15333333333332,
              new_customers_total_items: 8,
              total_items_cogs: 8,
              total_price_gross: 0,
              tax_refund: 0,
              discount_refund: 0,
            },
          },
          start: "2023-06-11T00:00:00+00:00",
          end: "2023-06-11T23:59:59+00:00",
          id: "Jun 11, 2023",
        },
      ],
    },
    handlingFees: 0,
    productCosts: 370.90999999999997,
    customSpends: [
      {
        end_date: 1632974400000,
        cost: "200000",
        recurring: false,
        title: "Overhead",
        start_date: 1630468800000,
        id: "zW5NVls4aav3MZoLes6A",
      },
      {
        end_date: 1635652800000,
        title: "SMS (Postscript)",
        percent: 1.5,
        metricId: "sales",
        start_date: 1633060800000,
        id: "62J44xaXZvVZK2YyDFrz",
      },
      {
        end_date: 1635652800000,
        cost: "175000",
        recurring: true,
        title: "Overhead",
        start_date: 1633060800000,
        id: "N66jpOhBHM30Ls3FWXKP",
      },
      {
        end_date: 1638248400000,
        cost: "125000",
        recurring: true,
        isAdSpend: false,
        title: "Overhead",
        start_date: 1635739200000,
        id: "j5hEv8RtkNflz6CFzhcO",
      },
      {
        end_date: 1638248400000,
        isAdSpend: true,
        title: "Postscript",
        percent: 1.5,
        metricId: "sales",
        start_date: 1635739200000,
        id: "xpOXPkckZS5cmDArKXY7",
      },
      {
        end_date: 1640926800000,
        cost: "155000",
        recurring: true,
        isAdSpend: false,
        title: "Overhead",
        start_date: 1638334800000,
        id: "Uz3TjwsrEQEEq5ZwIAWR",
      },
      {
        end_date: 1640926800000,
        cost: "15000",
        recurring: true,
        isAdSpend: false,
        title: "Buffer",
        start_date: 1638334800000,
        id: "WocqQVol4lTo8mcSVSx9",
      },
      {
        end_date: 1640926800000,
        isAdSpend: false,
        title: "Postscript",
        percent: 1.5,
        metricId: "sales",
        start_date: 1638334800000,
        id: "pw13Yk8pE9QXQz6PdTOd",
      },
      {
        end_date: 1643605200000,
        cost: "15000",
        recurring: true,
        isAdSpend: false,
        title: "Buffer",
        start_date: 1641013200000,
        id: "m5WlnqGNLRsmFYKw1pTU",
      },
      {
        end_date: 1643605200000,
        isAdSpend: true,
        title: "Postscript",
        percent: 1.5,
        metricId: "sales",
        start_date: 1641013200000,
        id: "xEIpeYRrDpcCSy1aqMkf",
      },
      {
        end_date: 1643605200000,
        cost: "140000",
        recurring: true,
        isAdSpend: false,
        title: "Overhead",
        start_date: 1641013200000,
        id: "yCS9mzapfUGiGrV1yZ7w",
      },
    ],
    mainDatePickerSelectionRange: {
      start: "2023-06-11T04:00:00.000Z",
      end: "2023-06-12T03:59:59.000Z",
    },
    shippingCosts: [
      {
        country_code: "US",
        shipping_cost: 8,
        id: "m9yIElOPE0MaFKMoItqD",
      },
    ],
    paymentGatewayCosts: [
      {
        name: "Afterpay",
        id: "Afterpay",
        cost: 5,
        fee: 0.3,
      },
      {
        name: "Authorize",
        id: "Authorize",
      },
      {
        name: "Authorize.Net Cim",
        id: "Authorize.Net Cim",
        cost: 0.1,
      },
      {
        name: "Braintree",
        id: "Braintree",
        cost: 3,
        fee: 0.3,
      },
      {
        name: "Klickly",
        id: "Klickly",
      },
      {
        name: "PayPal Checkout",
        id: "PayPal Checkout",
      },
      {
        name: "Sezzle Payments",
        id: "Sezzle Payments",
      },
      {
        name: "afterpay_north_america",
        id: "afterpay_north_america",
        cost: 5,
      },
      {
        name: "amazon_payments",
        id: "amazon_payments",
        cost: 3,
      },
      {
        name: "authorize_ch",
        id: "authorize_ch",
        cost: 3,
      },
      {
        name: "authorize_net",
        id: "authorize_net",
        cost: 3,
      },
      {
        name: "braintree",
        id: "braintree",
      },
      {
        name: "carro_stripe",
        id: "carro_stripe",
      },
      {
        name: "gift_card",
        id: "gift_card",
        cost: 3,
      },
      {
        name: "manual",
        id: "manual",
        cost: 3,
      },
      {
        name: "paypal",
        id: "paypal",
        cost: 3,
      },
      {
        name: "sezzle",
        id: "sezzle",
        cost: 6,
        fee: 0.3,
      },
      {
        name: "shop_cash",
        id: "shop_cash",
      },
      {
        name: "shopify_installments",
        id: "shopify_installments",
      },
      {
        name: "shopify_payments",
        id: "shopify_payments",
      },
    ],
    customMetrics: {
      metrics: [
        {
          metricType: "number",
          stat: [
            {
              type: "stat",
              value: "netSales",
              chart: "netSalesChart",
            },
            {
              type: "operator",
              value: "/",
            },
            {
              type: "stat",
              value: "blendedAds",
              chart: "chartBlendedAds",
            },
          ],
          description: "",
          section: "pinned",
          title: "net sales/ total ads spend",
          createdAt: {
            _seconds: 1661942721,
            _nanoseconds: 899000000,
          },
          id: "6L38bwHBRvWKGMklbEpT",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "nestedStat",
              chart: "customMetricsCharts",
              value: "customMetrics",
              statObjectKey: "XDlpY3ObEXkBNtESCGTZ",
            },
            {
              type: "operator",
              value: "+",
            },
            {
              type: "nestedStat",
              value: "customMetrics",
              chart: "customMetricsCharts",
              statObjectKey: "uauOrxRIDEQBBJJkFHrW",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Shipping CPO + COGS PO",
          createdAt: {
            _seconds: 1659359291,
            _nanoseconds: 338000000,
          },
          id: "I41lKG4ACkBr3f3ST4N2",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "nestedStat",
              chart: "customMetricsCharts",
              value: "customMetrics",
              statObjectKey: "I41lKG4ACkBr3f3ST4N2",
            },
            {
              type: "operator",
              value: "+",
            },
            {
              type: "stat",
              chart: "chartNewCustomersCpa",
              value: "newCustomersCpa",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Variable Expenses per New Order",
          createdAt: {
            _seconds: 1659359411,
            _nanoseconds: 627000000,
          },
          id: "OPRT7ak1z1YyzrgPSWWx",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "nestedStat",
              chart: "customMetricsCharts",
              value: "customMetrics",
              statObjectKey: "I41lKG4ACkBr3f3ST4N2",
            },
            {
              type: "operator",
              value: "+",
            },
            {
              type: "stat",
              chart: "chartShopifyCpa",
              value: "shopifyCpa",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Variable Expenses per Order",
          createdAt: {
            _seconds: 1659359325,
            _nanoseconds: 647000000,
          },
          id: "QhG75Cv0JLXxCZIkW3SM",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "stat",
              value: "shopifyAov",
              chart: "chartShopifyAov",
            },
            {
              type: "operator",
              value: "-",
            },
            {
              type: "nestedStat",
              value: "customMetrics",
              chart: "customMetricsCharts",
              statObjectKey: "QhG75Cv0JLXxCZIkW3SM",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Cont. Margin per Order",
          createdAt: {
            _seconds: 1659359358,
            _nanoseconds: 937000000,
          },
          id: "X7ANuQQK846E0PqFxxFe",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "stat",
              value: "totalProductCosts",
            },
            {
              type: "operator",
              value: "/",
            },
            {
              type: "stat",
              value: "totalOrders",
              chart: "chartOrders",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "COGS per order",
          createdAt: {
            _seconds: 1659359213,
            _nanoseconds: 291000000,
          },
          id: "XDlpY3ObEXkBNtESCGTZ",
        },
        {
          metricType: "$",
          expression: "field_80#+field_23#",
          stats: {
            "field_23#": {
              type: "stat",
              value: "totalReturns",
              chart: "totalReturnsChart",
            },
            "field_80#": {
              type: "stat",
              value: "blendedAds",
              chart: "chartBlendedAds",
            },
          },
          description: "try 1 desc",
          title: "Try 1",
          createdAt: {
            _seconds: 1683559393,
            _nanoseconds: 941000000,
          },
          id: "j9lMsp6olUZohex2yXKt",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "stat",
              value: "shopifyAov",
              chart: "chartShopifyAov",
            },
            {
              type: "operator",
              value: "-",
            },
            {
              type: "nestedStat",
              chart: "customMetricsCharts",
              value: "customMetrics",
              statObjectKey: "OPRT7ak1z1YyzrgPSWWx",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Contr. Margin per New Order",
          createdAt: {
            _seconds: 1659359435,
            _nanoseconds: 780000000,
          },
          id: "nmNtVOCg6TvqSGhrUoOi",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "stat",
              value: "newCustomersRoas",
            },
            {
              type: "operator",
              value: "*",
            },
            {
              type: "stat",
              chart: "chartNewCustomersCpa",
              value: "newCustomersCpa",
            },
          ],
          description: "",
          section: "pinned",
          title: "New Customer AOV",
          createdAt: {
            _seconds: 1669130025,
            _nanoseconds: 194000000,
          },
          id: "ttwm1nDHQ4iluWhgah0m",
        },
        {
          stat: [
            {
              type: "stat",
              chart: "chartSales",
              value: "totalSales",
            },
            {
              type: "operator",
              value: "/",
            },
            {
              type: "stat",
              chart: "chartOrders",
              value: "totalOrders",
            },
          ],
          description: "",
          section: "pinned",
          title: "AOV By Hour",
          metricType: "$",
          createdAt: {
            _seconds: 1638225961,
            _nanoseconds: 63000000,
          },
          id: "uBcU247PLBecmLdSUV4w",
        },
        {
          metricType: "$",
          stat: [
            {
              type: "stat",
              value: "totalShippingCosts",
              chart: "totalShippingCostsChart",
            },
            {
              type: "operator",
              value: "/",
            },
            {
              type: "stat",
              chart: "chartOrders",
              value: "totalOrders",
            },
          ],
          description: "",
          section: "Kc2Z1TwdXg5GX3LTThg8",
          title: "Shipping Cost per Order",
          createdAt: {
            _seconds: 1659359242,
            _nanoseconds: 273000000,
          },
          id: "uauOrxRIDEQBBJJkFHrW",
        },
      ],
    },
    shopTimezone: "America/New_York",
    shopifyUseMongoCogs: false,
    finance: {
      accounts: {
        "86": {
          ins_name: "",
          nickName: "Chase Bank x2159 (deleted)",
          type: "depository",
          provider: "codat",
        },
        "87": {
          ins_name: "",
          nickName: "Amex Plum x11002",
          type: "credit",
          provider: "codat",
        },
        "88": {
          ins_name: "",
          nickName: "Amex Gold x01004",
          type: "credit",
          provider: "codat",
        },
        "89": {
          ins_name: "",
          nickName: "Chase Ink x4905",
          type: "credit",
          provider: "codat",
        },
        "91": {
          ins_name: "",
          nickName: "New Era Media CC",
          type: "credit",
          provider: "codat",
        },
        "126": {
          ins_name: "",
          nickName: "PayPal x7778",
          type: "depository",
          provider: "codat",
        },
        "129": {
          ins_name: "",
          nickName: "Undeposited Funds",
          type: "credit",
          provider: "codat",
        },
        "139": {
          ins_name: "",
          nickName: "Chase Ink x4010",
          type: "credit",
          provider: "codat",
        },
        "143": {
          ins_name: "",
          nickName: "Amex Platinum x51003",
          type: "credit",
          provider: "codat",
        },
        "174": {
          ins_name: "",
          nickName: "Bill.com Money Out Clearing",
          type: "depository",
          provider: "codat",
        },
        "175": {
          ins_name: "",
          nickName: "Bill.com Money In Clearing",
          type: "depository",
          provider: "codat",
        },
        "186": {
          ins_name: "",
          nickName: "Settle Clearing Out",
          type: "depository",
          provider: "codat",
        },
        "187": {
          ins_name: "",
          nickName: "RHO Checking 4785",
          type: "depository",
          provider: "codat",
        },
        "188": {
          ins_name: "",
          nickName: "Rho Card #0672",
          type: "credit",
          provider: "codat",
        },
        "194": {
          ins_name: "",
          nickName: "Chase Savings x6229",
          type: "depository",
          provider: "codat",
        },
        "195": {
          ins_name: "",
          nickName: "Chase Operating x2159",
          type: "depository",
          provider: "codat",
        },
        "196": {
          ins_name: "",
          nickName: "Chase Large Ops x0393",
          type: "depository",
          provider: "codat",
        },
        "206": {
          ins_name: "",
          nickName: "Divvy Corporate Card",
          type: "credit",
          provider: "codat",
        },
        "294": {
          ins_name: "",
          nickName: "Parker Card",
          type: "credit",
          provider: "codat",
        },
        "335": {
          ins_name: "",
          nickName: "Brex Credit Card",
          type: "credit",
          provider: "codat",
        },
        "337": {
          ins_name: "",
          nickName: "Ramp Card",
          type: "credit",
          provider: "codat",
        },
        "341": {
          ins_name: "",
          nickName: "Mercury Checking x8349",
          type: "depository",
          provider: "codat",
        },
        "370": {
          ins_name: "",
          nickName: "Ramp-Flex.",
          type: "credit",
          provider: "codat",
        },
        peE96da3akt1qvVm95jEhXN3egYzexU4nEy3e: {
          ins_name: "Chase",
          nickName: "Payroll Large Ops",
          type: "depository",
          provider: "plaid",
          balances: [],
        },
        QV6naQxExzhLPK50X71Bu87J9yMn9mU4eYLO5: {
          ins_name: "Chase",
          nickName: "Operating",
          type: "depository",
          provider: "plaid",
          balances: [],
        },
        neOgdD919ytLzk5RxdKbux3BynLbyvtpJR3B8: {
          ins_name: "Chase",
          nickName: "R. SHAH",
          type: "credit",
          provider: "plaid",
          balances: [],
        },
        XO316MwDwzSyReA5mOX8TYK6ypxDyVsakAxd4: {
          ins_name: "Chase",
          nickName: "Savings",
          type: "depository",
          provider: "plaid",
          balances: [],
        },
      },
      codatTableRows: [],
      plaidTableRows: {
        creditRows: [],
        debitRows: [],
      },
      valuationCalculator: {
        valuation: "ebitdaValuation",
        calculator: 5,
      },
    },
  },
}
